enum ActionTypes {
    SET_FILTER_VALUE = 'SET_FILTER_VALUE',

    ADD_DATA_RECORD = 'ADD_DATA_RECORD',
    REMOVE_DATA_RECORD = 'REMOVE_DATA_RECORD',
    SET_DATA_RECORD = 'SET_DATA_RECORD',

    SET_FORM_DATA_LIST = 'SET_FORM_DATA_LIST',
    SET_FORM_RECORD = 'SET_FORM_RECORD',
    SET_FORM_NEW_RECORD = 'SET_FORM_NEW_RECORD',
    SET_FORM_NAME_RECORD = 'SET_FORM_NAME_RECORD',
    SET_FORM_COST_RECORD = 'SET_FORM_COST_RECORD',
} 

export { ActionTypes };